/*
 *
 *	Adventure Creator
 *	by Chris Burton, 2013-2020
 *	
 *	"GVar.cs"
 * 
 *	This script is a data class for project-wide variables.
 * 
 */

using UnityEngine;

namespace AC
{

	/**
	 * A data class for global and local variables.
	 * Variables are created in the Variables Manager asset file, and copied to the RuntimeVariables component when the game begins.
	 */
	[System.Serializable]
	public class GVar : ITranslatable
	{

		#region Variables

		/** Its editor name. */
		public string label;
		/** Its internal ID number. */
		public int id;
		/** Its variable type. */
		public VariableType type;
		/** Its value, if an integer, popup or boolean. If a boolean, 0 = False, and 1 = True. */
		public int val;
		/** Its value, if a float. */
		public float floatVal;
		/** Its value, if a string. */
		public string textVal;
		/** An array of labels, if a popup. */
		public string[] popUps;
		/** Its value, if a Vector3 */
		public Vector3 vector3Val;
		/** What it links to, if a Global or Compnent Variable.  A Variable can link to Options Data, or a Playmaker Variable. */
		public VarLink link = VarLink.None;
		/** If linked to a Playmaker Variable, the name of the PM variable. */
		public string pmVar;
		/** If True and linked to a PlayMaker Global Variable, then PM will be referred to for the initial value. */
		public bool updateLinkOnStart = false;
		/** If True, the variable's value can be translated (if PopUp or String) */
		public bool canTranslate = true;
		/** The ID number of the shared popup labels, if more than zero */
		public int popUpID = 0;

		/** The translation ID number of the variable's string value (if type == VariableType.String), as generated by SpeechManager */
		public int textValLineID = -1;
		/** The translation ID number of the variables's PopUp values (if type == VariableType.PopUp), as generated by SpeechManager */
		public int popUpsLineID = -1;

		private float backupFloatVal;
		private int backupVal;

		protected string[] runtimeTranslations;

		#if UNITY_EDITOR
		public string description = "";
		public bool showInFilter;
		#endif

		#endregion


		#region Constructors

		public GVar ()
		{}
		
		
		/**
		 * The main Constructor.
		 * An array of ID numbers is required, to ensure its own ID is unique.
		 */
		public GVar (int[] idArray)
		{
			val = 0;
			floatVal = 0f;
			textVal = "";
			type = VariableType.Boolean;
			link = VarLink.None;
			pmVar = "";
			popUps = null;
			updateLinkOnStart = false;
			backupVal = 0;
			backupFloatVal = 0f;
			textValLineID = -1;
			popUpsLineID = -1;
			canTranslate = true;
			vector3Val = Vector3.zero;
			popUpID = 0;

			AssignUniqueID (idArray);

			label = "Variable " + (id + 1).ToString ();

			#if UNITY_EDITOR
			description = "";
			#endif
		}
		

		/**
		 * A Constructor that copies all values from another variable.
		 * This way ensures that no connection remains to the asset file.
		 */
		public GVar (GVar assetVar)
		{
			val = assetVar.val;
			floatVal = assetVar.floatVal;
			textVal = assetVar.textVal;
			type = assetVar.type;
			id = assetVar.id;
			label = assetVar.label;
			link = assetVar.link;
			pmVar = assetVar.pmVar;
			popUps = assetVar.popUps;
			updateLinkOnStart = assetVar.updateLinkOnStart;
			backupVal = assetVar.val;
			backupFloatVal = assetVar.floatVal;
			textValLineID = assetVar.textValLineID;
			popUpsLineID = assetVar.popUpsLineID;
			canTranslate = assetVar.canTranslate;
			vector3Val = assetVar.vector3Val;
			popUpID = assetVar.popUpID;

			#if UNITY_EDITOR
			description = assetVar.description;
			#endif
		}

		#endregion


		#region PublicFunctions

		/**
		 * <summary>Sets the internal ID to a unique number based on an array of previously-used values</summary>
		 * <param name = "idArray">An array of previously-used ID values</param>
		 * <returns>The new ID number</returns>>
		 */
		public int AssignUniqueID (int[] idArray)
		{
			id = 0;

			if (idArray != null)
			{
				foreach (int _id in idArray)
				{
					if (id == _id)
					{
						id ++;
					}
				}
			}
			return id;
		}
		
		
		/**
		 * <summary>Sets its value to that of its linked variable (if appropriate).</summary>
		 * <param name = "_location">The variable's location</param>
		 * <param name = "_variables">The variable's Variables component, if location = VariableLocation.Component</param>
		 */
		public void Download (VariableLocation _location = VariableLocation.Global, Variables _variables = null)
		{
			if (_location == VariableLocation.Local) return;

			if (link == VarLink.PlaymakerVariable && !string.IsNullOrEmpty (pmVar))
			{
				if (!PlayMakerIntegration.IsDefinePresent ())
				{
					return;
				}

				if (_location != VariableLocation.Component) _variables = null;
				if (_location == VariableLocation.Component && _variables == null)
				{
					return;
				}

				switch (type)
				{
					case VariableType.Integer:
					case VariableType.PopUp:
						SetValue (PlayMakerIntegration.GetInt (pmVar, _variables));
						break;

					case VariableType.Boolean:
						bool _val = PlayMakerIntegration.GetBool (pmVar, _variables);
						SetValue ((_val) ? 1 : 0);
						break;

					case VariableType.String:
						SetStringValue (PlayMakerIntegration.GetString (pmVar, _variables));
						break;

					case VariableType.Float:
						SetFloatValue (PlayMakerIntegration.GetFloat (pmVar, _variables));
						break;

					case VariableType.Vector3:
						SetVector3Value (PlayMakerIntegration.GetVector3 (pmVar, _variables));
						break;
				}
			}
			else if (link == VarLink.CustomScript)
			{
				KickStarter.eventManager.Call_OnDownloadVariable (this, _variables);
			}
		}
		
		
		/**
		 * <summary>Sets the value of its linked variable to its value (if appropriate).</summary>
		 * <param name = "_location">The variable's location</param>
		 * <param name = "_variables">The variable's Variables component, if location = VariableLocation.Component</param>
		 */
		public void Upload (VariableLocation _location = VariableLocation.Global, Variables _variables = null)
		{
			if (_location == VariableLocation.Local) return;

			if (link == VarLink.PlaymakerVariable && !string.IsNullOrEmpty (pmVar))
			{
				if (!PlayMakerIntegration.IsDefinePresent ())
				{
					return;
				}

				if (_location != VariableLocation.Component) _variables = null;
				if (_location == VariableLocation.Component && _variables == null)
				{
					return;
				}

				switch (type)
				{
					case VariableType.Integer:
					case VariableType.PopUp:
						PlayMakerIntegration.SetInt (pmVar, val, _variables);
						break;

					case VariableType.Boolean:
						PlayMakerIntegration.SetBool (pmVar, (val == 1), _variables);
						break;

					case VariableType.String:
						PlayMakerIntegration.SetString (pmVar, textVal, _variables);
						break;

					case VariableType.Float:
						PlayMakerIntegration.SetFloat (pmVar, floatVal, _variables);
						break;

					case VariableType.Vector3:
						PlayMakerIntegration.SetVector3 (pmVar, vector3Val, _variables);
						break;
				}
			}
			else if (link == VarLink.OptionsData)
			{
				Options.SavePrefs ();
			}
			else if (link == VarLink.CustomScript)
			{
				KickStarter.eventManager.Call_OnUploadVariable (this, _variables);
			}
		}
		

		/**
		 * Backs up its value.
		 * Necessary when skipping ActionLists that involve checking variable values.
		 */
		public void BackupValue ()
		{
			backupVal = val;
			backupFloatVal = floatVal;
		}
		
		
		/**
		 * Restores its value from backup. 
		 * Necessary when skipping ActionLists that involve checking variable values.
		 */
		public void RestoreBackupValue ()
		{
			val = backupVal;
			floatVal = backupFloatVal;
		}
		
		
		/**
		 * <summary>Sets the value if its type is String.</summary>
		 * <param name = "newValue">The new value of the string</param>
		 * <param name = "newLineID">If >=0, the translation ID used by SpeechManager / RuntimeLanguages will be updated to this value</param>
		 */
		public void SetStringValue (string newValue, int newLineID = -1)
		{
			TextValue = newValue;

			if (type == VariableType.String && newLineID >= 0)
			{
				textValLineID = newLineID;
				CreateRuntimeTranslations ();
			}
		}
		
		
		/**
		 * <summary>Sets the value if its type is Float.</summary>
		 * <param name = "newValue">The new float value</param>
		 * <param name = "setVarMethod">How the new value affects the old (replaces, increases by, or randomises)</param>
		 */
		public void SetFloatValue (float newValue, SetVarMethod setVarMethod = SetVarMethod.SetValue)
		{
			float originalValue = floatVal;

			if (setVarMethod == SetVarMethod.IncreaseByValue)
			{
				FloatValue = originalValue + newValue;
			}
			else if (setVarMethod == SetVarMethod.SetAsRandom)
			{
				FloatValue = Random.Range (0f, newValue);
			}
			else
			{
				FloatValue = newValue;
			}
		}


		/**
		 * <summary>Sets the value if its type is Vector3.</summary>
		 * <param name = "newValue">The new Vector3 value</param>
		 */
		public void SetVector3Value (Vector3 newValue)
		{
			Vector3Value = newValue;
		}
		

		/**
		 * <summary>Sets the value if its type is Integer, Boolean or PopUp.</summary>
		 * <param name = "newValue">The new integer value</param>
		 * <param name = "setVarMethod">How the new value affects the old (replaces, increases by, or randomises)</param>
		 */
		public void SetValue (int newValue, SetVarMethod setVarMethod = SetVarMethod.SetValue)
		{
			if (setVarMethod == SetVarMethod.IncreaseByValue)
			{
				newValue = IntegerValue + newValue;
			}
			else if (setVarMethod == SetVarMethod.SetAsRandom)
			{
				newValue = Random.Range (0, newValue);
			}

			if (type == VariableType.Boolean)
			{
				BooleanValue = (newValue > 0);
				return;
			}
			else if (type == VariableType.PopUp)
			{
				newValue = Mathf.Clamp (newValue, 0, GetNumPopUpValues () - 1);
			}

			IntegerValue = newValue;
		}


		/**
		 * <summary>Transfers translation data from RuntimeLanguages to the variable itself. This allows it to be transferred to other variables with the 'Variable: Copy' Action.</summary>
		 */
		public void CreateRuntimeTranslations ()
		{
			runtimeTranslations = null;

			if (HasTranslations ())
			{
				if (type == VariableType.String && canTranslate)
				{
					runtimeTranslations = KickStarter.runtimeLanguages.GetTranslations (textValLineID);
				}
				else if (type == VariableType.PopUp)
				{
					int translationID = -1;
					if (popUpID > 0)
					{
						PopUpLabelData popUpLabelData = KickStarter.variablesManager.GetPopUpLabelData (popUpID);
						if (popUpLabelData != null && popUpLabelData.CanTranslate ())
						{
							translationID = popUpLabelData.LineID;
							canTranslate = true;
						}
					}
					else if (canTranslate)
					{
						translationID = popUpsLineID;
					}
					runtimeTranslations = KickStarter.runtimeLanguages.GetTranslations (translationID);
				}
			}
		}


		/**
		 * <summary>Gets the variable's translations, if they exist.</summary>
		 * <returns>The variable's translations, if they exist, as an array.</summary>
		 */
		public string[] GetTranslations ()
		{
			return runtimeTranslations;
		}


		/**
		 * <summary>Copies the value of another variable onto itself.</summary>
		 * <param name = "oldVar">The variable to copy from</param>
		 * <param name = "oldLocation">The location of the variable to copy (Global, Local)</param>
		 */
		public void CopyFromVariable (GVar oldVar, VariableLocation oldLocation)
		{
			if (oldLocation == VariableLocation.Global)
			{
				oldVar.Download (oldLocation);
			}

			if (type == VariableType.Integer || type == VariableType.Boolean || type == VariableType.PopUp)
			{
				int oldValue = oldVar.val;

				if (oldVar.type == VariableType.Float)
				{
					oldValue = (int) oldVar.floatVal;
				}
				else if (oldVar.type == VariableType.String)
				{
					float oldValueAsFloat = 0f;
					float.TryParse (oldVar.textVal, out oldValueAsFloat);
					oldValue = (int) oldValueAsFloat;
				}

				if (type == VariableType.PopUp && oldVar.HasTranslations ())
				{
					runtimeTranslations = oldVar.GetTranslations ();
				}
				else
				{
					runtimeTranslations = null;
				}

				SetValue (oldValue, SetVarMethod.SetValue);
			}
			else if (type == VariableType.Float)
			{
				float oldValue = oldVar.floatVal;

				if (oldVar.type == VariableType.Integer || oldVar.type == VariableType.Boolean || oldVar.type == VariableType.PopUp)
				{
					oldValue = (float) oldVar.val;
				}
				else if (oldVar.type == VariableType.String)
				{
					float.TryParse (oldVar.textVal, out oldValue);
				}

				SetFloatValue (oldValue, AC.SetVarMethod.SetValue);
			}
			else if (type == VariableType.String)
			{
				string oldValue = oldVar.GetValue ();
				textVal = oldValue;

				if (oldVar.HasTranslations ())
				{
					runtimeTranslations = oldVar.GetTranslations ();
				}
				else
				{
					runtimeTranslations = null;
				}
			}
			else if (type == VariableType.Vector3)
			{
				Vector3 oldValue = oldVar.vector3Val;
				vector3Val = oldValue;
			}
		}
		
		
		/**
		 * <summary>Returns the variable's value.</summary>
		 * <returns>The value, as a formatted string.</returns>
		 */
		public string GetValue (int languageNumber = 0)
		{
			if (!canTranslate)
			{
				languageNumber = 0;
			}

			if (type == VariableType.Integer)
			{
				return val.ToString ();
			}
			else if (type == VariableType.PopUp)
			{
				return GetPopUpForIndex (val, languageNumber);
			}
			else if (type == VariableType.String)
			{
				if (languageNumber > 0)
				{
					if (runtimeTranslations == null)
					{
						CreateRuntimeTranslations ();
					}
					if (runtimeTranslations != null && runtimeTranslations.Length >= languageNumber)
					{
						return runtimeTranslations[languageNumber-1];
					}
				}
				return textVal;
			}
			else if (type == VariableType.Float)
			{
				return floatVal.ToString ();
			}
			else if (type == VariableType.Vector3)
			{
				return "(" + vector3Val.x.ToString () + ", " + vector3Val.y.ToString () + ", " + vector3Val.z.ToString () + ")";
			}
			else
			{
				if (val == 0)
				{
					return "False";
				}
				else
				{
					return "True";
				}
			}
		}


		/**
		 * <summary>Gets all possible PopUp values as a single string, where the values are separated by a ']' character.</summary>
		 * <returns>All possible PopUp values as a single string, where the values are separated by a ']' character.</returns>
		 */
		public string GetPopUpsString ()
		{
			if (popUpID > 0)
			{
				PopUpLabelData popUpLabelData = KickStarter.variablesManager.GetPopUpLabelData (popUpID);
				if (popUpLabelData != null)
				{
					return popUpLabelData.GetPopUpsString ();
				}
				return string.Empty;
			}

			string result = string.Empty;
			foreach (string popUp in popUps)
			{
				result += popUp + "]";
			}
			if (result.Length > 0)
			{
				return result.Substring (0, result.Length-1);
			}
			return string.Empty;
		}


		/**
		 * <summary>Checks if the Variable is translatable.</summary>
		 * <returns>True if the Variable is translatable</returns>
		 */
		public bool HasTranslations ()
		{
			if (type == VariableType.String || type == VariableType.PopUp)
			{
				return canTranslate;
			}
			return false;
		}


		/**
		 * <summary>Checks if this Variable is defined under the Variable Manager's list of Global Variables</summary>
		 * <returns>True if the variable is Global</returns> 
		 */
		public bool IsGlobalVariable ()
		{
			foreach (GVar gVar in KickStarter.runtimeVariables.globalVars)
			{
				if (gVar == this)
				{
					return true;
				}
			}
			return false;
		}


		/**
		 * <summary>Gets the number of possible values, if of the type PopUp</summary>
		 * <returns>The number of possible values, if of the type PopUp</returns>
		 */
		public int GetNumPopUpValues ()
		{
			if (popUpID <= 0)
			{
				if (popUps != null)
				{
					return popUps.Length;
				}
			}
			else if (KickStarter.variablesManager != null)
			{
				PopUpLabelData popUpLabelData = KickStarter.variablesManager.GetPopUpLabelData (popUpID);
				if (popUpLabelData != null)
				{
					return popUpLabelData.Length;
				}
			}
			return 0;
		}


		/**
		 * <summary>Gets the PopUp value of a given index and language, if of type PopUp</summary>
		 * <param name = "index">The index of the PopUp labels</param>
		 * <param name = "language">The language index</param>
		 * <returs>The PopUp value of a given index and language</returns>
		 */
		public string GetPopUpForIndex (int index, int language = 0)
		{
			if (index >= 0)
			{
				if (language > 0 && runtimeTranslations == null)
				{
					CreateRuntimeTranslations ();
				}
				if (language > 0 && runtimeTranslations != null && runtimeTranslations.Length >= language)
				{
					string popUpsString = runtimeTranslations[language-1];
					string[] popUpsNew = popUpsString.Split ("]"[0]);
					if (index < popUpsNew.Length)
					{
						return popUpsNew[index];
					}
				}
				else if (popUpID > 0)
				{
					PopUpLabelData popUpLabelData = KickStarter.variablesManager.GetPopUpLabelData (popUpID);
					if (popUpLabelData != null)
					{
						return popUpLabelData.GetValue (index);
					}
				}
				else if (popUps != null && index < popUps.Length)
				{
					return popUps[index];
				}
			}
			return string.Empty;
		}

		#endregion


		#region GetSet

		/** Its value, if an integer. */
		public int IntegerValue
		{
			get
			{
				return val;
			}
			set
			{
				int originalValue = val;

				val = value;

				if (originalValue != val)
				{
					KickStarter.eventManager.Call_OnVariableChange (this);
				}
			}
		}


		/** Its value, if a boolean. */
		public bool BooleanValue
		{
			get
			{
				return (val == 1);
			}
			set
			{
				int originalValue = val;

				val = (value) ? 1 : 0;

				if (originalValue != val)
				{
					KickStarter.eventManager.Call_OnVariableChange (this);
				}
			}
		}


		/** Its value, if a float. */
		public float FloatValue
		{
			get
			{
				return floatVal;
			}
			set
			{
				float originalValue = floatVal;

				floatVal = value;

				if (!Mathf.Approximately (originalValue, floatVal))
				{
					KickStarter.eventManager.Call_OnVariableChange (this);
				}
			}
		}


		/** Its value, if a string. */
		public string TextValue
		{
			get
			{
				return textVal;
			}
			set
			{
				string originalValue = textVal;

				textVal = value;

				if (originalValue != textVal)
				{
					KickStarter.eventManager.Call_OnVariableChange (this);
				}
			}
		}


		/** Its value, if a Vector3. */
		public Vector3 Vector3Value
		{
			get
			{
				return vector3Val;
			}
			set
			{
				Vector3 originalValue = vector3Val;

				vector3Val = value;

				if (originalValue != vector3Val)
				{
					KickStarter.eventManager.Call_OnVariableChange (this);
				}
			}
		}

		#endregion


		#region ITranslatable

		public virtual string GetTranslatableString (int index)
		{
			if (type == VariableType.String)
			{
				return textVal;
			}
			else
			{
				return GetPopUpsString ();
			}
		}


		public virtual int GetTranslationID (int index)
		{
			if (type == VariableType.String)
			{
				return textValLineID;
			}
			else
			{
				return popUpsLineID;
			}
		}
		

		public virtual AC_TextType GetTranslationType (int index)
		{
			return AC_TextType.Variable;
		}


		#if UNITY_EDITOR

		public int GetNumTranslatables ()
		{
			return 1;
		}


		public virtual bool HasExistingTranslation (int index)
		{
			if (type == VariableType.String)
			{
				return textValLineID > -1;
			}
			else
			{
				return popUpsLineID > -1;
			}
		}


		public virtual void SetTranslationID (int index, int _lineID)
		{
			if (type == VariableType.String)
			{
				textValLineID = _lineID;
			}
			else
			{
				popUpsLineID = _lineID;
			}
		}


		public string GetOwner (int index)
		{
			return string.Empty;
		}


		public bool OwnerIsPlayer (int index)
		{
			return false;
		}


		public virtual bool CanTranslate (int index)
		{
			if (canTranslate)
			{
				if (type == VariableType.String)
				{
					return !string.IsNullOrEmpty (textVal);
				}
				else if (type == VariableType.PopUp && popUpID <= 0)
				{
					return !string.IsNullOrEmpty (GetPopUpsString ());
				}
			}
			return false;
		}


		public string[] GenerateEditorPopUpLabels ()
		{
			string[] popUpLabels = new string[GetNumPopUpValues ()];
			for (int i=0; i<popUpLabels.Length; i++)
			{
				popUpLabels[i] = GetPopUpForIndex (i);
				if (string.IsNullOrEmpty (popUpLabels[i]))
				{
					popUpLabels[i] = "(Unnamed)";
				}
				//popUpLabels[i] = i + ": " + popUpLabels[i];
			}

			return popUpLabels;
		}

		#endif

		#endregion

	}

}